name: Percy

on: push

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run Percy build
        run: npm test
        env:
          PERCY_TOKEN: web_6c86991a228357d8a47cc8c6e64d3edf42d0a1d86f511c605053d2a62198af5e
          PERCY_CLIENT_API_URL: https://percy.io/api/v1/
