name: Percy

on: push

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run Percy build
        run: npm test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_CLIENT_API_URL: https://staging.percy.dev/api/v1/
